version: '3.8'

services:

  mysql-kidsstore:
    image: mysql:8.0
    container_name: kidsstore-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: KidsStore
      MYSQL_USER: kiduser
      MYSQL_PASSWORD: kidspass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kidsstore-phpmyadmin
    environment:
      PMA_HOST: mysql-kidsstore
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    restart: unless-stopped
    depends_on:
      - mysql-kidsstore

volumes:
  mysql_data: